site_name: ADF CLI docs
nav:
  - Introdução: http://localhost:8000/
  - Instalação: instalacao.md
  - Configuração: configuracao.md
  - Comandos: commands.md
  - Detalhes de implementação: detalhes_de_implementacao.md
  - Autores: authors.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
  font:
    text: Roboto
  
repo_url: https://github.com/karlosdaniel451/adf-cli


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
